### ISSUE TITLE
Building on Ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by thetornadotitan** [Mitchzof/stratiom#2]
Running:
Building on Ubuntu 18.04.2 LTS
node version: v11.14.0

When attempting to run the build through npm I get the follow stack trace error:

```
> stratiom@1.0.0 build /home/isaac/Projects/stellarwebwallet/stratiom
> gulp prod

fs.js:25
'use strict';
^

ReferenceError: internalBinding is not defined
    at fs.js:25:1
    at req_ (/home/isaac/Projects/stellarwebwallet/stratiom/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/home/isaac/Projects/stellarwebwallet/stratiom/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/home/isaac/Projects/stellarwebwallet/stratiom/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stratiom@1.0.0 build: `gulp prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the stratiom@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/isaac/.npm/_logs/2019-05-09T07_27_46_906Z-debug.log
```

I've tried with and without running npm audit fix
I've installed the additional dependencies mentioned at the end of the npm install step.

fsevents gives this error, not sure if it related:

```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.0.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/isaac/.npm/_logs/2019-05-09T07_26_34_987Z-debug.log
```

I like the look of the website and wanted to use this for a project. Any suggestions?

**Comment by thetornadotitan** [comment]
Downgraded to LTS instead of latest. Josh is a whore. It works now
